# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0026_auto_20170220_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Leave blank if not applicable', verbose_name='Do you have any other dietary restrictions we should be aware of (e.g. vegetarian, gluten-free, etc.)? We can accommodate ANY and ALL dietary needs as long as we know in advance.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='food_allergies',
            field=models.TextField(blank=True, help_text='Leave blank if not applicable', verbose_name="Please list any food allergies you have (e.g. peanuts, shellfish). Describe what happens when you come into contact with this allergen (e.g. 'I get hives,' 'I go into anaphylactic shock')."),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Leave blank if not applicable', verbose_name='Do you have any other medical conditions, past injuries, disabilities or other allergies that we should be aware of? Please describe any injury, condition, disability, or illness which we should take into consideration in assigning you a trip'),
        ),
    ]
