# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0029_auto_20170221_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
