# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


def flip_med_info_value(apps, schema_editor):
    IncomingStudent = apps.get_model('incoming', 'IncomingStudent')
    for inc in IncomingStudent.objects.all():
        inc.hide_med_info = not inc.hide_med_info
        inc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0030_auto_20170526_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingstudent',
            old_name='show_med_info',
            new_name='hide_med_info'
        ),
        migrations.AlterField(
            model_name='incomingstudent',
            name='hide_med_info',
            field=models.BooleanField(default=False, help_text="Checking this box will cause medical information in this trippee's registration to *not* be displayed in leader and croo packets.", verbose_name='Hide registration med info?'),
        ),
        migrations.RunPython(flip_med_info_value)
    ]
