# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0031_auto_20170811_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingstudent',
            name='hinman_box',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
