# Generated by Django 2.0.2 on 2018-03-10 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incoming', '0033_auto_20180112_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('trips_year', 'user')},
        ),
    ]
