# Generated by Django 2.1.5 on 2019-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0035_auto_20180412_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='epipen',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Do you carry an EpiPen? If yes, please bring it with you on Trips.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='has_boating_experience',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Have you ever been on an overnight or extended canoe or kayak trip?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_exchange',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you an Exchange Student?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_fysep',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you participating in the First Year Student Enrichment Program (FYSEP)?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_international',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you an International Student who plans on attending the International Student Orientation?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_native',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you a Native American Student who plans on attending the Native American student orientation?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_transfer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you a Transfer Student?'),
        ),
    ]
