# Generated by Django 2.2.6 on 2020-02-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0038_auto_20190524_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Leave blank if not applicable', verbose_name='Do you have any other medical conditions, past injuries, ability-related concerns, other allergies, or personal concerns (regarding your own physical/mental/emotional health) that would be relevant to your role as a trip leader or crooling (in trip placement, completing trainings, participating in a croo, etc.)? This information is requested to help us place you in a position you feel comfortable. Again, this entire section will not be considered during the grading of your application.'),
        ),
    ]
