# Generated by Django 3.1.11 on 2021-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0039_auto_20200214_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='financial_assistance',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name="Are you requesting financial assistance from First-Year Trips? If 'yes' we will contact you in July with more information about your financial assistance."),
        ),
    ]
