# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0070_auto_20170408_1046'),
        ('core', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.Training'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='sessions',
            field=models.ManyToManyField(to='training.Session'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='trips_year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.Volunteer'),
        ),
    ]
