# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20170412_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='complete_sessions',
            field=models.ManyToManyField(blank=True, related_name='attended', to='training.Session'),
        ),
    ]
