# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20170417_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
