# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20170417_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='first_aid',
            field=models.BooleanField(default=False),
        ),
    ]
