# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 15:03
from __future__ import unicode_literals

from django.db import migrations


def create_attendees(apps, schema_editor):
    Volunteer = apps.get_model('applications', 'Volunteer')
    Attendee = apps.get_model('training', 'Attendee')

    for v in Volunteer.objects.all():
        Attendee.objects.get_or_create(
            trips_year=v.trips_year, volunteer=v)


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_attendee_first_aid'),
        ('applications', '0070_auto_20170408_1046'),
    ]

    operations = [
        migrations.RunPython(create_attendees)
    ]
