# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20170418_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date', 'training']},
        ),
    ]
