# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20170419_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='first_aid',
        ),
    ]
