# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_remove_attendee_first_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
