# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_session_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='fa_cert',
            field=models.CharField(blank=True, choices=[(None, '--'), ('FA', 'First Aid'), ('CPR', 'CPR'), ('FA/CPR', 'First Aid/CPR'), ('WFA', 'WFA'), ('WFR', 'WFR'), ('W-EMT', 'W-EMT'), ('EMT', 'EMT'), ('OEC', 'OEC'), ('other', 'other')], default='', max_length=10, verbose_name='first aid cert'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='fa_other',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='other first aid cert'),
        ),
    ]
