# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 17:42
from __future__ import unicode_literals

from django.db import migrations


def move_first_aid_certs(apps, schema_editor):

    Volunteer = apps.get_model('applications', 'Volunteer')
    for v in Volunteer.objects.all():
        a = v.attendee
        a.fa_cert = v.fa_cert
        a.fa_other = v.fa_other
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20170425_1341'),
        ('applications', '0070_auto_20170408_1046'),
    ]

    operations = [
        migrations.RunPython(move_first_aid_certs)
    ]
