# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20170425_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['volunteer']},
        ),
    ]
