# Generated by Django 2.0.1 on 2018-01-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20170428_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='applications.Volunteer'),
        ),
    ]
