# Generated by Django 2.0.2 on 2018-03-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('applications', '0074_auto_20180302_1204'),
        ('training', '0019_auto_20180112_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[(None, '--'), ('FA', 'First Aid'), ('CPR', 'CPR'), ('FA/CPR', 'First Aid/CPR'), ('WFA', 'WFA'), ('WFR', 'WFR'), ('W-EMT', 'W-EMT'), ('EMT', 'EMT'), ('OEC', 'OEC'), ('other', 'other')], default='', max_length=10)),
                ('other', models.CharField(blank=True, default='', max_length=100, verbose_name='other first aid cert')),
                ('expiration_date', models.DateField()),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.Volunteer')),
            ],
            options={
                'ordering': ['volunteer'],
            },
        ),
    ]
