# Generated by Django 2.0.2 on 2018-03-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20180303_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidcertification',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_aid_certifications', to='applications.Volunteer'),
        ),
    ]
