# Generated by Django 2.0.2 on 2018-03-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_auto_20180305_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstaidcertification',
            options={'ordering': ['volunteer', 'pk']},
        ),
    ]
