# Generated by Django 2.0.4 on 2018-04-13 01:08

from django.db import migrations

from datetime import time

YEARS = [2015, 2016]


def move_legacy_training_data(apps, schema_editor):
    Attendee = apps.get_model('training', 'Attendee')
    Training = apps.get_model('training', 'Training')
    Session = apps.get_model('training', 'Session')
    TripsYear = apps.get_model('core', 'TripsYear')

    noon = time(12)

    for trips_year in TripsYear.objects.filter(year__in=YEARS):
        cb = Training.objects.create(trips_year=trips_year,
                                     name='Community building')
        rm = Training.objects.create(trips_year=trips_year,
                                     name='Risk management')
        ws = Training.objects.create(trips_year=trips_year,
                                     name='Wilderness skills')

        for a in Attendee.objects.filter(trips_year=trips_year):

            def make_sesh(training, date):
                if not date:
                    return None
                return Session.objects.get_or_create(
                    trips_year=trips_year,
                    training=training,
                    date=date,
                    start_time=noon,
                    end_time=noon)[0]

            sessions = [
                make_sesh(cb, a.volunteer.community_building),
                make_sesh(rm, a.volunteer.risk_management),
                make_sesh(ws, a.volunteer.wilderness_skills)]

            a.complete_sessions.set([s for s in sessions if s is not None])
            a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20180305_1245'),
        ('applications', '0107_auto_20180412_1932'),
    ]

    operations = [
        migrations.RunPython(move_legacy_training_data)
    ]
