# Generated by Django 2.0.4 on 2018-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20180412_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidcertification',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified?'),
        ),
    ]
