# Generated by Django 2.0.6 on 2018-07-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20180717_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='fa_cert',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='fa_other',
        ),
    ]
