# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20161029_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadersupplement',
            old_name='available_sections',
            new_name='_old_available_sections',
        ),
        migrations.RenameField(
            model_name='leadersupplement',
            old_name='available_triptypes',
            new_name='_old_available_triptypes',
        ),
        migrations.RenameField(
            model_name='leadersupplement',
            old_name='preferred_sections',
            new_name='_old_preferred_sections',
        ),
        migrations.RenameField(
            model_name='leadersupplement',
            old_name='preferred_triptypes',
            new_name='_old_preferred_triptypes',
        ),
    ]
