# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_generalapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinformation',
            name='application_questions',
            field=models.FileField(default='', help_text='.docx file', upload_to='', verbose_name='Application questions'),
            preserve_default=False,
        ),
    ]
