# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicationinformation_application_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalapplication',
            name='croo_willing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I would like to be considered for a Croo posision. I understand...'),
        ),
        migrations.AddField(
            model_name='generalapplication',
            name='leader_willing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I would like to be considered for a Trip Leader position. I understand... (describe commitments, etc.)'),
        ),
    ]
