# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 18:49
from __future__ import unicode_literals

from django.db import migrations

"""
Populate the `croo_willing' and 'leader_willing' fields of old
applications setting them to True if the applicant submitted a
Croo or Leader application, respectively.
"""

def populate_willing_fields(apps, schema_editor):
    Application = apps.get_model('applications', 'GeneralApplication')

    for app in Application.objects.all():
        app.leader_willing = bool(app.leader_supplement.document)
        app.croo_willing = bool(app.croo_supplement.document)
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20170122_1343'),
    ]

    operations = [
        migrations.RunPython(populate_willing_fields)
    ]
