# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20170122_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croosupplement',
            old_name='document',
            new_name='_old_document',
        ),
        migrations.RenameField(
            model_name='leadersupplement',
            old_name='document',
            new_name='_old_document',
        ),
    ]
