# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20170122_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationinformation',
            old_name='croo_info',
            new_name='_old_croo_info',
        ),
        migrations.RenameField(
            model_name='applicationinformation',
            old_name='croo_supplement_questions',
            new_name='_old_croo_supplement_questions',
        ),
        migrations.RenameField(
            model_name='applicationinformation',
            old_name='general_info',
            new_name='_old_general_info',
        ),
        migrations.RenameField(
            model_name='applicationinformation',
            old_name='leader_info',
            new_name='_old_leader_info',
        ),
        migrations.RenameField(
            model_name='applicationinformation',
            old_name='leader_supplement_questions',
            new_name='_old_leader_supplement_questions',
        ),
    ]
