# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import fyt.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20170122_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='trainings',
            field=models.BooleanField(default=False, validators=[fyt.applications.models.validate_condition_true], verbose_name='I understand that if I am accepted as a Trips volunteer I will be required to get First Aid and CPR training, as well as attend croo- and leader-specific trainings. I understand that if I do not meet these requirements, I will not be able to volunteer for Trips.'),
        ),
        migrations.AlterField(
            model_name='generalapplication',
            name='trippee_confidentiality',
            field=models.BooleanField(default=False, validators=[fyt.applications.models.validate_condition_true], verbose_name="If selected to be a Trips volunteer, I understand that I will be given access to Trippees' confidential medical information for safety purposes. I pledge to maintain the confidentiality of this information, except as is required by medical or legal concerns"),
        ),
    ]
