# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_applicationquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.GeneralApplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationQuestion')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('application', 'question')]),
        ),
    ]
