# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20170125_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationquestion',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='index',
            field=models.PositiveIntegerField(unique=True, verbose_name='the order of the questions'),
        ),
    ]
