# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20170125_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalapplication',
            name='answers',
            field=models.ManyToManyField(through='applications.Answer', to='applications.ApplicationQuestion'),
        ),
    ]
