# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_generalapplication_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationQuestion',
            new_name='Question',
        ),
    ]
