# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20170126_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalapplication',
            name='document',
        ),
    ]
