# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_remove_generalapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalapplication',
            name='gear',
            field=models.TextField(blank=True, verbose_name='What outdoor gear is available to you? Will you be able to borrow gear from friends and family or will you need assistance from DOC Trips to find gear?'),
        ),
        migrations.AddField(
            model_name='generalapplication',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='generalapplication',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
