# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20170217_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='croo_willing',
            field=models.BooleanField(verbose_name='I would like to be considered for a crooling position. (NOTE: ‘19s who are taking classes this sophomore summer can NOT apply, given the conflict of dates.)'),
        ),
        migrations.AlterField(
            model_name='generalapplication',
            name='leader_willing',
            field=models.BooleanField(verbose_name='I would like to be considered for a trip leader position. '),
        ),
        migrations.AlterField(
            model_name='generalapplication',
            name='role_preference',
            field=models.CharField(choices=[('PREFER_LEADER', 'Prefer Trip Leader'), ('PREFER_CROO', 'Prefer Crooling'), ('N/A', 'N/A')], default='N/A', max_length=20, verbose_name="While Trips Directorate will place you, we would like to know your preferences. If you are submitting a Trip Leader application AND a Crooling application, please indicate which position you prefer. If you are only applying to one position, please choose 'N/A'"),
        ),
    ]
