# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20170220_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='race_ethnicity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Race/Ethnicity'),
        ),
        migrations.AlterField(
            model_name='generalapplication',
            name='summer_address',
            field=models.CharField(blank=True, help_text='Tell us your home address if you are not yet sure of your summer address.', max_length=255),
        ),
    ]
