# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_generalapplication_transfer_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Based on your prior knowledge of and experience with Trips, do you have any suggestions to improve the program? If so, what? Remember that this question is ungraded and optional, but your feedback will help us improve the program for incoming students!'),
        ),
    ]
