# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_auto_20170220_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='personal_activities',
            field=models.TextField(blank=True, verbose_name='In order of importance to you, please list your activities, involvements, and communities at Dartmouth and beyond (e.g. greek affiliation, affinity group, campus organization, team, etc)'),
        ),
    ]
