# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_auto_20170220_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='gear',
            field=models.TextField(blank=True, verbose_name='Most trips require participants to have a frame pack, sleeping bag, and sleeping pad. What outdoor gear is available to you? Will you be able to borrow gear from friends and family or will you require rentals from DOC Trips?  While we will do our best to accommodate your gear needs if you are selected, priority will be given to first-years.'),
        ),
    ]
