# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_auto_20170220_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersupplement',
            name='bike_maintenance_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any experience you have with bike maintenance.'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='biking_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any relevant mountain biking experience you have.'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='class_2_3_paddler',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Can you comfortably paddle Class II/III rapids?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='climbing_course',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you taken a DOC-sponsored top rope course/anchor building course, or do you plan to take one before fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='climbing_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any relevant climbing experience you have.'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='dmbc_leader',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a leader in the Mountain Biking Club or will you become one before fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='dmc_leader',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a Dartmouth Mountaineering Club leader or will you become one before the fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='ledyard_level_1',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a Level I Ledyard whitewater kayaking leader or anticipate becoming one before the fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='ledyard_level_2',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a Level II Ledyard whitewater kayaking leader or anticipate becoming one before the fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='paddling_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any relevant kayaking or canoeing experience you have.'),
        ),
    ]
