# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_auto_20170220_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersupplement',
            name='relevant_experience',
            field=models.TextField(blank=True, verbose_name='WITHOUT repeating anything you have already told us, please describe your level of expertise and any previous experience that you could bring to each trip type that you selected (e.g. lifeguard training, yoga experience, meditation experience, fishing experience, photography class, Walden enthusiast, NOLS, Cabin and Trail leader, etc).'),
        ),
    ]
