# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20170220_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersupplement',
            name='co_leader',
            field=models.TextField(blank=True, verbose_name='Please describe the qualities you would seek in an ideal co-leader. Be candid so we can best pair you.'),
        ),
    ]
