# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_leadersupplement_co_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersupplement',
            name='availability',
            field=models.TextField(blank=True, verbose_name='Looking at the Trips descriptions, please feel free to use this space to address any concerns or explain your availability. If applicable, please also elaborate on any particular trips or activities that you absolutely CANNOT participate in. All information in this application will remain confidential.'),
        ),
    ]
