# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:55
from __future__ import unicode_literals

from django.db import migrations


def combine_fields(apps, schema_editor):
    """
    Combine the contents of the `trip_preference_comments` and
    `cannot_participate_in` fields into the `availability` field.
    """

    LeaderSupplement = apps.get_model('applications', 'LeaderSupplement')

    for ls in LeaderSupplement.objects.all():
        ls.availability = "{}\r\n{}".format(
            ls.trip_preference_comments, ls.cannot_participate_in
        )
        ls.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_leadersupplement_availability'),
    ]

    operations = [
        migrations.RunPython(combine_fields)
    ]
