# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0047_auto_20170220_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersupplement',
            name='biking_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any mountain biking experience you have.'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='climbing_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any climbing experience you have.'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='paddling_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any kayaking or canoeing experience you have.'),
        ),
    ]
