# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_auto_20170221_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersupplement',
            name='cnt_leader',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a Cabin and Trail leader or will you become one before the fall term?'),
        ),
        migrations.AddField(
            model_name='leadersupplement',
            name='hiking_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any hiking experience you have.'),
        ),
    ]
