# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_auto_20170221_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersectionchoice',
            name='preference',
            field=models.CharField(choices=[('PREFER', 'prefer'), ('AVAILABLE', 'available'), ('NOT AVAILABLE', 'not available')], default='NOT AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadertriptypechoice',
            name='preference',
            field=models.CharField(choices=[('PREFER', 'prefer'), ('AVAILABLE', 'available'), ('NOT AVAILABLE', 'not available')], default='NOT AVAILABLE', max_length=20),
        ),
    ]
