# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_auto_20170221_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='from_where',
            field=models.CharField(max_length=255, verbose_name='Hometown'),
        ),
    ]
