# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_auto_20170221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('ALL', 'All applicants'), ('LEADER', 'Leader applicants only'), ('CROO', 'Croo applicants only')], default='ALL', max_length=10, verbose_name='Is this a question for all applicants, leader applicants, or croo applicants?'),
        ),
    ]
