# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import fyt.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, validators=[fyt.applications.models.validate_word_count]),
        ),
    ]
