# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_remove_generalapplication_leadership_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersupplement',
            name='availability',
            field=models.TextField(blank=True, verbose_name="Looking at the Trips descriptions, please feel free to use this space to address any concerns or explain your availability. (Attention '19s: If you are available for more than Sections H, I, and J, please explain how.) If applicable, please also elaborate on any particular trips or activities that you absolutely CANNOT participate in. All information in this application will remain confidential."),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='relevant_experience',
            field=models.TextField(blank=True, verbose_name='WITHOUT repeating anything you have already told us, please describe your level of expertise and any previous experience that you could bring to each trip type that you selected (e.g. lifeguard training, yoga experience, meditation experience, fishing experience, photography class, Walden enthusiast, etc).'),
        ),
    ]
