# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_auto_20170227_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralApplication',
            new_name='Volunteer',
        ),
    ]
