# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0061_auto_20170308_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='hometown',
            field=models.CharField(max_length=255),
        ),
    ]
