# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0062_auto_20170308_1334'),
        ('applications', '0061_score_skip'),
    ]

    operations = [
    ]
