# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0063_merge_20170308_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('grader', 'application')]),
        ),
        migrations.AlterUniqueTogether(
            name='skip',
            unique_together=set([('grader', 'application')]),
        ),
    ]
