# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0064_auto_20170308_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='croo_head',
            field=models.BooleanField(default=False, editable=False, verbose_name='was the score created by a croo head?'),
        ),
    ]
