# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0065_score_croo_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='general',
            field=models.TextField(default='', verbose_name='Given the notes you made above, please explain the holistic score that you assigned. If applicable, please note if the applicant is better qualified to be a trip leader or crooling, and please note any identities.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='question1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='question2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='question3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='question4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='question5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='question6',
            field=models.TextField(blank=True),
        ),
    ]
