# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0066_auto_20170331_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question1',
            field=models.TextField(blank=True, verbose_name='question 1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question2',
            field=models.TextField(blank=True, verbose_name='question 2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question3',
            field=models.TextField(blank=True, verbose_name='question 3'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question4',
            field=models.TextField(blank=True, verbose_name='question 4'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question5',
            field=models.TextField(blank=True, verbose_name='question 5'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question6',
            field=models.TextField(blank=True, verbose_name='question 6'),
        ),
    ]
