# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 21:20
from __future__ import unicode_literals

from django.db import migrations


def normalize_class_year(apps, schema_editor):
    Volunteer = apps.get_model('applications', 'Volunteer')
    for v in Volunteer.objects.all():
        if len(str(v.class_year)) == 2:
            target = int('20{}'.format(v.class_year))
            print('converting {} to {}'.format(v.class_year, target))
            v.class_year = target
            v.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0067_auto_20170331_1835'),
    ]

    operations = [
        migrations.RunPython(normalize_class_year)
    ]
