# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 21:44
from __future__ import unicode_literals

from django.db import migrations
import fyt.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0068_auto_20170407_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='class_year',
            field=fyt.applications.models.ClassYearField(),
        ),
    ]
