# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0069_auto_20170407_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='skip',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='skip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
