# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0070_auto_20170408_1046'),
        ('training', '0017_auto_20170425_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='fa_cert',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='fa_other',
        ),
    ]
