# Generated by Django 2.0.1 on 2018-01-12 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0071_auto_20170425_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crooapplicationgrade',
            name='application',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='applications.CrooSupplement'),
        ),
        migrations.AlterField(
            model_name='crooapplicationgrade',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='crooapplicationgrades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='croosupplement',
            name='application',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='croo_supplement', to='applications.Volunteer'),
        ),
        migrations.AlterField(
            model_name='leaderapplicationgrade',
            name='application',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='applications.LeaderSupplement'),
        ),
        migrations.AlterField(
            model_name='leaderapplicationgrade',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='leaderapplicationgrades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='application',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='leader_supplement', to='applications.Volunteer'),
        ),
        migrations.AlterField(
            model_name='score',
            name='application',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='applications.Volunteer'),
        ),
        migrations.AlterField(
            model_name='score',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skippedcroograde',
            name='for_qualification',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.QualificationTag'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='applicant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
