# Generated by Django 2.0.2 on 2018-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0072_auto_20180112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='croo_willing',
            field=models.BooleanField(verbose_name='I would like to be considered for a crooling position. (NOTE: students who are taking classes this sophomore summer can NOT apply, given the conflict of dates.)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='leader_willing',
            field=models.BooleanField(verbose_name='I would like to be considered for a trip leader position.'),
        ),
    ]
