# Generated by Django 2.0.2 on 2018-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0073_auto_20180221_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('ALL', 'All applicants'), ('LEADER', 'Leader applicants only'), ('CROO', 'Croo applicants only'), ('OPTIONAL', 'Optional')], default='ALL', max_length=10, verbose_name='Is this a question for all applicants, leader applicants, croo applicants, or is it optional?'),
        ),
    ]
