# Generated by Django 2.0.2 on 2018-03-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0078_auto_20180310_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Answer')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Score')),
            ],
            options={
                'ordering': ['answer'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='comments',
            field=models.ManyToManyField(through='applications.AnswerComment', to='applications.Answer'),
        ),
    ]
