# Generated by Django 2.0.3 on 2018-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0078_auto_20180310_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='deadline_extension',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
