# Generated by Django 2.0.3 on 2018-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0079_volunteer_deadline_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='deadline_extension',
            field=models.DateTimeField(blank=True, help_text='Extension to the application deadline', null=True),
        ),
    ]
