# Generated by Django 2.0.2 on 2018-03-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0080_auto_20180321_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question6',
        ),
    ]
