# Generated by Django 2.0.2 on 2018-03-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0081_auto_20180321_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answercomment',
            unique_together={('score', 'answer')},
        ),
    ]
