# Generated by Django 2.0.3 on 2018-03-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_dartmouthuser_email2'),
        ('applications', '0085_remove_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.dartmouthuser',),
        ),
        migrations.AlterField(
            model_name='score',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='applications.Grader'),
        ),
        migrations.AlterField(
            model_name='skip',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='applications.Grader'),
        ),
    ]
