# Generated by Django 2.0.3 on 2018-04-02 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('applications', '0086_auto_20180327_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='score_claims', to='applications.Volunteer')),
                ('grader', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='applications.Grader')),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scoreclaim',
            unique_together={('grader', 'application')},
        ),
    ]
