# Generated by Django 2.0.3 on 2018-04-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0088_auto_20180402_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreclaim',
            name='grader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='score_claims', to='applications.Grader'),
        ),
    ]
