# Generated by Django 2.0.3 on 2018-04-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0089_auto_20180402_1742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoreclaim',
            unique_together=set(),
        ),
    ]
