# Generated by Django 2.0.3 on 2018-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0090_auto_20180403_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreclaim',
            name='croo_head',
            field=models.BooleanField(default=False, editable=False, verbose_name='is the grader a croo head?'),
        ),
    ]
