# Generated by Django 2.0.4 on 2018-04-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('applications', '0091_scoreclaim_croo_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
