# Generated by Django 2.0.4 on 2018-04-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0092_scorequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.ScoreQuestion'),
            preserve_default=False,
        ),
    ]
