# Generated by Django 2.0.4 on 2018-04-05 22:30

from django.db import migrations

TARGET_YEAR = 2017

"""
Create an ScoreQuestion object for each application question in 2017.
"""

def link_comments_to_score_question(apps, schema_editor):
    AnswerComment = apps.get_model('applications', 'AnswerComment')
    ScoreQuestion = apps.get_model('applications', 'ScoreQuestion')
    Question      = apps.get_model('applications', 'Question')

    question_to_score_question = {
        q : ScoreQuestion.objects.create(
                question='Question {}'.format(q.pk),
                order=q.index,
                trips_year=q.trips_year)
            for q in Question.objects.filter(trips_year=TARGET_YEAR)
    }

    for comment in AnswerComment.objects.filter(score__trips_year=TARGET_YEAR):
        comment.question = question_to_score_question[comment.answer.question]
        comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0093_answercomment_question')
    ]

    operations = [
        migrations.RunPython(link_comments_to_score_question)
    ]
