# Generated by Django 2.0.4 on 2018-04-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0096_auto_20180405_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercomment',
            options={'ordering': ['question']},
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.ScoreQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='answercomment',
            unique_together={('score', 'question')},
        ),
    ]
