# Generated by Django 2.0.4 on 2018-04-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0098_auto_20180405_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='answer',
        ),
    ]
