# Generated by Django 2.0.4 on 2018-04-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0099_remove_answercomment_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerComment',
            new_name='ScoreComment',
        ),
    ]
