# Generated by Django 2.0.4 on 2018-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0101_auto_20180406_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='croo_score',
            field=models.DecimalField(blank=True, choices=[(1, "1 -- Bad application -- I really don't want this person to be a volunteer and I have serious concerns"), (1.5, '1.5'), (2, '2 -- Poor application -- I have some concerns about this person being a Trips volunteer'), (2.5, '2.5'), (3, '3 -- Fine application -- This person might work well as a volunteer but I have some questions'), (3.5, '3.5'), (4, "4 -- Good application -- I would consider this person to be a volunteer but I wouldn't be heartbroken if they were not selected"), (4.5, '4.5'), (5, '5 -- Great application -- I think this person would be a fantastic volunteer')], decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='leader_score',
            field=models.DecimalField(blank=True, choices=[(1, "1 -- Bad application -- I really don't want this person to be a volunteer and I have serious concerns"), (1.5, '1.5'), (2, '2 -- Poor application -- I have some concerns about this person being a Trips volunteer'), (2.5, '2.5'), (3, '3 -- Fine application -- This person might work well as a volunteer but I have some questions'), (3.5, '3.5'), (4, "4 -- Good application -- I would consider this person to be a volunteer but I wouldn't be heartbroken if they were not selected"), (4.5, '4.5'), (5, '5 -- Great application -- I think this person would be a fantastic volunteer')], decimal_places=1, max_digits=2, null=True),
        ),
    ]
