# Generated by Django 2.0.4 on 2018-04-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0102_auto_20180406_0758'),
        ('applications', '0081_auto_20180405_1011'),
    ]

    operations = [
    ]
