# Generated by Django 2.0.4 on 2018-04-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0103_merge_20180406_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecomment',
            options={'ordering': ['score_question']},
        ),
        migrations.RenameField(
            model_name='scorecomment',
            old_name='question',
            new_name='score_question',
        ),
        migrations.AlterUniqueTogether(
            name='scorecomment',
            unique_together={('score', 'score_question')},
        ),
    ]
