# Generated by Django 2.0.4 on 2018-04-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0104_auto_20180409_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crooapplicationgrade',
            name='application',
        ),
        migrations.RemoveField(
            model_name='crooapplicationgrade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='crooapplicationgrade',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='crooapplicationgrade',
            name='trips_year',
        ),
        migrations.RemoveField(
            model_name='leaderapplicationgrade',
            name='application',
        ),
        migrations.RemoveField(
            model_name='leaderapplicationgrade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='leaderapplicationgrade',
            name='trips_year',
        ),
        migrations.RemoveField(
            model_name='qualificationtag',
            name='trips_year',
        ),
        migrations.RemoveField(
            model_name='skippedcroograde',
            name='application',
        ),
        migrations.RemoveField(
            model_name='skippedcroograde',
            name='for_qualification',
        ),
        migrations.RemoveField(
            model_name='skippedcroograde',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='skippedcroograde',
            name='trips_year',
        ),
        migrations.RemoveField(
            model_name='skippedleadergrade',
            name='application',
        ),
        migrations.RemoveField(
            model_name='skippedleadergrade',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='skippedleadergrade',
            name='trips_year',
        ),
        migrations.DeleteModel(
            name='CrooApplicationGrade',
        ),
        migrations.DeleteModel(
            name='LeaderApplicationGrade',
        ),
        migrations.DeleteModel(
            name='QualificationTag',
        ),
        migrations.DeleteModel(
            name='SkippedCrooGrade',
        ),
        migrations.DeleteModel(
            name='SkippedLeaderGrade',
        ),
    ]
