# Generated by Django 2.0.4 on 2018-04-12 16:27

from django.db import migrations
import logging


log = logging.getLogger(__name__)


def fixup_unique_collisions(apps, schema_editor):
    ScoreClaim = apps.get_model('applications', 'ScoreClaim')

    to_delete = set()

    for claim in ScoreClaim.objects.all():
        duplicates = ScoreClaim.objects.filter(
            grader=claim.grader, application=claim.application
        ).order_by('-claimed_at')[1:]

        if duplicates.exists():
            log.info('Deleting %s', duplicates)
            to_delete.update(duplicates)

    for claim in to_delete:
        claim.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0105_auto_20180409_1556'),
    ]

    operations = [
        migrations.RunPython(fixup_unique_collisions),
        migrations.AlterUniqueTogether(
            name='scoreclaim',
            unique_together={('grader', 'application')},
        ),
    ]
