# Generated by Django 2.0.4 on 2018-04-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0105_auto_20180409_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoreclaim',
            unique_together={('grader', 'application')},
        ),
    ]
