# Generated by Django 2.0.4 on 2018-04-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0107_auto_20180412_1932'),
        ('training', '0025_auto_20180412_2108')
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='community_building',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='croo_training',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='risk_management',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='wilderness_skills',
        ),
    ]
