# Generated by Django 2.0.4 on 2018-04-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0108_auto_20180412_2152'),
        ('applications', '0104_auto_20180407_1211'),
    ]

    operations = [
    ]
