# Generated by Django 2.0.4 on 2018-04-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('applications', '0109_merge_20180413_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.CharField(max_length=512, blank=True)),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
