# Generated by Django 2.0.4 on 2018-04-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('applications', '0111_auto_20180413_1306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorevalue',
            unique_together={('value', 'trips_year')},
        ),
    ]
