# Generated by Django 2.0.4 on 2018-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0112_auto_20180413_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='croo_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='leader_score',
        ),
    ]
