# Generated by Django 2.0.4 on 2018-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0113_auto_20180413_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='fk_croo_score',
            new_name='croo_score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='fk_leader_score',
            new_name='leader_score',
        ),
    ]
