# Generated by Django 2.0.4 on 2018-04-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0114_auto_20180413_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='assigned_trip',
            new_name='trip_assignment',
        ),
    ]
