# Generated by Django 2.0.4 on 2018-04-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0115_auto_20180416_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='assigned_croo',
            new_name='croo_assignment',
        ),
    ]
