# Generated by Django 2.1.5 on 2019-01-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0116_auto_20180416_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='submitted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
