# Generated by Django 2.1.5 on 2019-01-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0117_volunteer_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='in_goodstanding_with_college',
            field=models.BooleanField(default=False, verbose_name='By applying to volunteer for Trips, I acknowledge that I am in good standing with the College. This will be verified by DOC Trips through the Undergraduate Dean’s Office.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='trainings',
            field=models.BooleanField(default=False, verbose_name='I understand that if I am accepted as a Trips volunteer I will be required to get First Aid and CPR training, as well as attend croo- and leader-specific trainings. I understand that if I do not meet these requirements, I will not be able to volunteer for Trips.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='trippee_confidentiality',
            field=models.BooleanField(default=False, verbose_name="If selected to be a Trips volunteer, I understand that I will be given access to Trippees' confidential medical information for safety purposes. I pledge to maintain the confidentiality of this information, except as is required by medical or legal concerns"),
        ),
    ]
