# Generated by Django 2.1.5 on 2019-01-23 12:25

from django.db import migrations, models
import fyt.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0120_volunteer_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='class_year',
            field=fyt.applications.models.ClassYearField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hinman_box',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hometown',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3),
        ),
    ]
