# Generated by Django 2.1.5 on 2019-01-23 22:41

from django.db import migrations
import fyt.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0121_auto_20190123_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='class_year',
            field=fyt.applications.models.ClassYearField(blank=True, null=True),
        ),
    ]
