# Generated by Django 2.1.5 on 2019-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0122_auto_20190123_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='croo_willing',
            field=models.BooleanField(default=False, verbose_name='I would like to be considered for a crooling position. (NOTE: students who are taking classes this sophomore summer can NOT apply, given the conflict of dates.)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='leader_willing',
            field=models.BooleanField(default=False, verbose_name='I would like to be considered for a trip leader position.'),
        ),
    ]
