# Generated by Django 2.1.5 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0124_auto_20190125_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'man'), ('FEMALE', 'woman'), ('NON_BINARY', 'nonbinary'), ('OTHER', 'other')], max_length=25),
        ),
    ]
