# Generated by Django 2.1.5 on 2019-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0125_auto_20190201_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('LATINO', 'Latino/a/x'), ('NATIVE', 'Native American/Alaskan'), ('PACIFIC_ISLANDER', 'Pacific Islander/Native Hawaiian'), ('EAST_ASIAN', 'East Asian'), ('SOUTH_ASIAN', 'South Asian'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('MIXED_RACE', 'Mixed Race'), ('OTHER', 'Other')], max_length=255, verbose_name='Race/Ethnicity'),
        ),
    ]
