# Generated by Django 2.1.5 on 2019-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0127_leadersupplement_swim_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croosupplement',
            name='can_get_certified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='If you are not certified, are you able to go through the College’s sprinter van & mini-bus driver certification process this spring or summer term?'),
        ),
        migrations.AlterField(
            model_name='croosupplement',
            name='college_certified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you a college-certified driver?'),
        ),
        migrations.AlterField(
            model_name='croosupplement',
            name='licensed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name="Do you have a valid driver's license?"),
        ),
        migrations.AlterField(
            model_name='croosupplement',
            name='microbus_certified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you microbus certified?'),
        ),
        migrations.AlterField(
            model_name='croosupplement',
            name='sprinter_certified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Are you sprinter van certified?'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='swim_test',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Have you passed the Dartmouth swim test?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='epipen',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Do you carry an EpiPen? If yes, please bring it with you on Trips.'),
        ),
    ]
