# Generated by Django 2.2.6 on 2020-02-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0129_auto_20190214_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersupplement',
            name='availability',
            field=models.TextField(blank=True, verbose_name='Looking at the Trips descriptions, please feel free to use this space to address any concerns you might have about leading certain trips. All information in this application will remain confidential.'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='dmbc_leader',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you a leader in the Dartmouth Mountain Biking Club or will you become one before fall term?'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='paddling_experience',
            field=models.TextField(blank=True, verbose_name='Please describe any kayaking or canoeing experience you have, including flatwater.'),
        ),
        migrations.AlterField(
            model_name='leadersupplement',
            name='relevant_experience',
            field=models.TextField(blank=True, verbose_name='WITHOUT repeating anything you have already told us, please describe any expertise or previous experience (if you have it) that you could bring to trip types you selected (e.g. lifeguard training, yoga experience, meditation experience, fishing experience, photography class, Walden enthusiast, etc).'),
        ),
        migrations.AlterField(
            model_name='leadertriptypechoice',
            name='preference',
            field=models.CharField(choices=[('PREFER', 'prefer'), ('AVAILABLE', 'willing'), ('NOT AVAILABLE', 'unwilling/unable')], default='NOT AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'man'), ('FEMALE', 'woman'), ('NON_BINARY', 'nonbinary'), ('OTHER', 'other'), ('DECLINE', 'decline to answer')], max_length=25, verbose_name='Gender Identity'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hanover_in_fall',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'Unsure')], default=None, null=True, verbose_name='Are you planning to be in Hanover this fall?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, verbose_name="Where would you say you're from? (physical location please)"),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Leave blank if not applicable', verbose_name='Do you have any other medical conditions, past injuries, ability-related concerns, other allergies, or personal concerns (regarding your own physical/mental/emotional health) that would be relevant to your role as a trip leader or crooling (in trip placement, completing trainings, participating in a croo, etc.)? This information is requested to help us place you in a position you feel comfortable. Again, this entire section will not be considered during the grading of your application.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='personal_activities',
            field=models.TextField(blank=True, verbose_name='In order of importance to you, please list your activities, involvements, and communities at Dartmouth and beyond.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('LATINO', 'Latino/a/x'), ('NATIVE', 'Native American/Alaskan'), ('PACIFIC_ISLANDER', 'Pacific Islander/Native Hawaiian'), ('EAST_ASIAN', 'East Asian'), ('SOUTH_ASIAN', 'South Asian'), ('SOUTH_EAST_ASIAN', 'Southeast Asian'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('MIXED_RACE', 'Mixed Race'), ('OTHER', 'Other')], max_length=255, verbose_name='Race/Ethnicity'),
        ),
    ]
