# Generated by Django 2.2.6 on 2020-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0130_auto_20200214_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersupplement',
            name='section_availability',
            field=models.TextField(blank=True, verbose_name='First-year students who plan to attend pre-orientation programs (FYSEP, Native and Indigenous Orientation, International Student Orientation, Transfer/Exchange Students) will be placed on particular sections. If you would like to lead a trip on a section with these students, please indicate your preference here.'),
        ),
    ]
