# Generated by Django 3.1.11 on 2021-05-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0131_auto_20200219_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='croo_willing',
            field=models.BooleanField(default=False, verbose_name='I would like to be considered for a crooling position.'),
        ),
    ]
