# Generated by Django 3.1.11 on 2021-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0132_auto_20210518_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gear',
            field=models.TextField(blank=True, verbose_name='Most trips require participants to have a frame pack, sleeping bag, and sleeping pad. What outdoor gear is available to you? Will you be able to borrow gear from friends and family or will you require rentals from First-Year Trips?  While we will do our best to accommodate your gear needs if you are selected, priority will be given to first-years.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='in_goodstanding_with_college',
            field=models.BooleanField(default=False, verbose_name='By applying to volunteer for Trips, I acknowledge that I am in good standing with the College. This will be verified by First-Year Trips through the Undergraduate Dean’s Office.'),
        ),
    ]
