# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_auto_20170807_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptemplate',
            name='return_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returning_trips', to='transport.Route'),
        ),
    ]
