# Generated by Django 2.0.2 on 2018-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_auto_20180112_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sophomore_leaders_ok',
            field=models.BooleanField(default=False, verbose_name='Will sophomores taking classes this summer be able to lead trips during this section?'),
        ),
    ]
