# Generated by Django 2.0.5 on 2018-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_auto_20180304_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_fysep',
            field=models.BooleanField(default=False, verbose_name='FYSEP'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_international',
            field=models.BooleanField(default=False, verbose_name='International'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_native',
            field=models.BooleanField(default=False, verbose_name='Native'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Transfer'),
        ),
    ]
