# Generated by Django 2.0.7 on 2018-07-25 22:43

from django.db import migrations, models


def trim_packing_list(apps, schema_editor):

    TripType = apps.get_model('trips', 'TripType')

    print()

    for triptype in TripType.objects.all():

        # Backup old packing list
        triptype.old_packing_list = triptype.packing_list
        triptype.save()

        # Cut out essential, individual info
        start = triptype.packing_list.find('PERSONAL GEAR')
        end = triptype.packing_list.find('OPTIONAL')

        if -1 in [start, end]:
            print('Chunk not found: {} {}'.format(triptype.name, triptype.trips_year))

        triptype.packing_list = triptype.packing_list[start:end].strip()
        triptype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_auto_20180522_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptype',
            name='old_packing_list',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(trim_packing_list)
    ]
