# Generated by Django 2.1 on 2018-08-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180719_1052'),
        ('trips', '0021_triptype_old_packing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTemplateDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
                ('day1', models.TextField(blank=True, verbose_name='Day 1')),
                ('day2', models.TextField(blank=True, verbose_name='Day 2')),
                ('day3', models.TextField(blank=True, verbose_name='Day 3')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion')),
                ('revisions', models.TextField(blank=True)),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='description',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.TripTemplateDescription'),
        ),
    ]
