# Generated by Django 2.1 on 2018-08-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_auto_20180822_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triptemplate',
            name='desc_conc',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='desc_day1',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='desc_day2',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='desc_day3',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='desc_intro',
        ),
        migrations.RemoveField(
            model_name='triptemplate',
            name='revisions',
        ),
        migrations.AlterField(
            model_name='triptemplate',
            name='description',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='trips.TripTemplateDescription'),
        ),
    ]
