# Generated by Django 2.0.6 on 2018-06-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0116_auto_20180416_1613'),
        ('incoming', '0035_auto_20180412_1932'),
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='gearrequest',
            name='incoming_student',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='incoming.IncomingStudent'),
        ),
        migrations.AddField(
            model_name='gearrequest',
            name='volunteer',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.Volunteer'),
        ),
    ]
