# Generated by Django 2.1 on 2018-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_auto_20180813_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearrequest',
            name='provided_comments',
            field=models.TextField(blank=True, help_text='Add information here about why gear is not being provided, if applicable', verbose_name='additional comments'),
        ),
    ]
