# Generated by Django 2.1 on 2018-08-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_auto_20180813_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearrequest',
            options={'ordering': ['incoming_student', 'volunteer']},
        ),
    ]
