# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('transport', '0003_auto_20170305_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.Stop')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.Stop')),
                ('trips_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.TripsYear')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transportconfig',
            unique_together=set([('trips_year',)]),
        ),
    ]
