# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 16:28
from __future__ import unicode_literals

from django.db import migrations


def init_transport_config(apps, schema_editor):
    """
    Initialize lodge, hanover, and TransportConfig objects for each
    trips_year.
    """
    TransportConfig = apps.get_model('transport', 'TransportConfig')
    Stop = apps.get_model('transport', 'Stop')
    TripsYear = apps.get_model('db', 'TripsYear')

    for trips_year in TripsYear.objects.filter(year__in=[2015, 2016, 2017]):

       hanover = Stop.objects.create(
           trips_year=trips_year,
           name='Hanover, NH',
           address='6 N Main St, Hanover, NH 03755',
           distance=0)

       lodge = Stop.objects.create(
           trips_year=trips_year,
           name='The Moosilauke Ravine Lodge',
           lat_lng='43.977253,-71.8154831',
           distance=10000)

       config = TransportConfig.objects.create(
           trips_year=trips_year,
           hanover=hanover,
           lodge=lodge)


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20170714_1227'),
    ]

    operations = [
        migrations.RunPython(init_transport_config)
    ]
