# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20170714_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledTransport',
            new_name='InternalBus',
        ),
        migrations.AlterField(
            model_name='route',
            name='category',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('INTERNAL', 'External')], max_length=20),
        ),
    ]
