# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20170715_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='category',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=20),
        ),
    ]
