# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_route_display_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoporder',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
