# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_stoporder_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoporder',
            old_name='time',
            new_name='computed_time'
        ),
        migrations.AlterField(
            model_name='stoporder',
            name='computed_time',
            field=models.TimeField('Pickup/dropoff time computed by Google Maps', null=True, editable=False)
        )
    ]
