# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20170808_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbus',
            name='dirty',
            field=models.BooleanField(default=True, editable=False, verbose_name='Do directions and times need to be updated?'),
        ),
    ]
