# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_internalbus_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbus',
            name='custom_times',
            field=models.BooleanField(default=False, verbose_name='Are pickup and dropoff times for this bus input manually?'),
        ),
    ]
