# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_internalbus_custom_times'),
        ('transport', '0015_stoporder_custom_time'),
    ]

    operations = [
    ]
