# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_auto_20170821_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalbus',
            name='notes',
            field=models.TextField(blank=True, help_text='for the bus driver'),
        ),
    ]
