# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_auto_20170821_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoporder',
            name='custom_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Custom pickup/dropoff time'),
        ),
    ]
