# Generated by Django 2.1 on 2018-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_auto_20170822_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chartered',
            field=models.BooleanField(default=False, help_text='Is this bus chartered through a bus company?'),
        ),
    ]
