# Generated by Django 2.1 on 2018-08-19 16:37

from django.db import migrations


def mark_chartered_buses(apps, schema_editor):
    Vehicle = apps.get_model('transport', 'Vehicle')

    qs = Vehicle.objects.filter(
        name__in=['Internal Bus', 'External Bus']
    )
    for v in qs:
        print(v, v.trips_year)

    qs.update(chartered=True)


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_vehicle_chartered'),
    ]

    operations = [
        migrations.RunPython(mark_chartered_buses)
    ]
