# Generated by Django 2.2 on 2019-04-29 21:48

from django.db import migrations


def add_user_profile(apps, schema_editor):
    DartmouthUser = apps.get_model("users", "DartmouthUser")
    UserProfile = apps.get_model("users", "UserProfile")

    for user in DartmouthUser.objects.all():
        UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile'),
    ]

    operations = [
        migrations.RunPython(add_user_profile)
    ]
