# Generated by Django 2.0.6 on 2018-07-19 14:52

from django.db import migrations

'''
Clean out some old database tables that were not properly migrated.
'''

tables = [
    'leaders_leaderapplication',
    'leaders_leaderapplication_available_sections',
    'leaders_leaderapplication_available_triptypes',
    'leaders_leaderapplication_preferred_sections',
    'leaders_leaderapplication_preferred_triptypes',
    'leaders_leadergrade',
    'db_cost',
    'trippees_address',
    'trippees_incomingstudent',
    'trippees_registration',
    'trippees_registration_available_sections',
    'trippees_registration_available_triptypes',
    'trippees_registration_preferred_sections',
    'trippees_registration_preferred_triptypes',
    'trippees_registration_unavailable_sections',
    'trippees_registration_unavailable_triptypes',
]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS %s CASCADE;' % tablename)
        for tablename in tables
    ]
