# Generated by Django 2.0.1 on 2018-01-12 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_auto_20150909_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='leave blank if incident did not occur on a trip', null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.Trip', verbose_name='On what trip did this incident occur?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
