# Generated by Django 2.0.4 on 2018-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_scoring_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='scoring_available',
            field=models.BooleanField(default=False, help_text='Turn this on to begin the scoring process. Only do so once all applications have been submitted. Applications with extensions will not be scored until the extension deadline has passed. Graders will have access to the scoring page when this is enabled.'),
        ),
    ]
